apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::502170355984:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-26OV2XSM9W14
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::502170355984:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-04-24T16:23:58Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1839"
  uid: 532e9ba1-2f8a-4432-b079-82e6d1372b0f
